name: Release Package

# on:
#   release:
#     types: [created]
on:
  push:
    branches: [test-publish]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - working-directory: packages/snap
        run: |
          yarn install
          yarn lint

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - working-directory: packages/snap
        run: |
          yarn install
          yarn publish-build
      - name: Publish
        working-directory: packages/snap
        env:
          NODE_AUTH_TOKEN: ${{secrets.CLUSTERS_SDK_NPM_TOKEN}}
        run: npm publish --dry-run
